### ISSUE TITLE
What is the difference between idiap's approach and Kaldi's approach?

### ISSUE THREAD

**Issue by StevenLOL** [idiap/kaldi-ivector#1]
Can give more info about the difference of the two approaches?

**Comment by mrsrikanth** [comment]
Hello Steve,

We have implemented the standard T-matrix
estimation and the corresponding i-vector extraction
procedures (see [1]), which to my knowledge is not available
for Kaldi. I believe the existing code in kaldi is based on the SGMM
setup (see [2] as pointed out by the code).

We will soon upload our report describing the implementation and
differences.
- Srikanth

[1] Glembek, Ondřej, et al. "Simplification and optimization of i-vector
extraction." _Acoustics, Speech and Signal Processing (ICASSP), 2011 IEEE
International Conference on_. IEEE, 2011.
[2] http://www.sciencedirect.com/science/article/pii/S088523081000063X

**Comment by StevenLOL** [comment]
Thanks
