### ISSUE TITLE
Does this repo still work with the latest Kaldi (5.3)?

### ISSUE THREAD

**Issue by MaigoAkisame** [idiap/kaldi-ivector#4]
I tried to make this repo, but found that this repo depended on many things in the "src/thread" folder of Kaldi, which does not exist in the latest version of Kaldi.

For example:
* The Makefiles refer to ${KALDI_DIR}/src/thread/kaldi-thread.a, but this seems to have moved to ${KALDI_DIR}/src/util/kaldi-thread.o.
* The conv-ivector-extractor.h file includes "thread/kaldi-mutex.h", which no longer exists (nor is there any files with the same name in Kaldi). The Mutex class in the code seems to have been replaced by std::mutex.

So I wonder if this repo still works with the latest Kaldi?

**Comment by nishkalavallabhi** [comment]
It did not work for me. I saw a couple of no such file or directory messages. 
![kaldi-ivector](https://user-images.githubusercontent.com/7221440/33780810-b6b56c4a-dc17-11e7-9eb3-7939dde0f087.png)

**Comment by mrsrikanth** [comment]
Hello,

Thank you for reporting this. Yes, I confirm that it doesn't work
on the latest Kaldi. I will work on fixing this in the coming weeks.

Thanks,
Srikanth

**Comment by MaigoAkisame** [comment]
Thanks!

**Comment by ajinkyakulkarni14** [comment]
On which version of Kaldi this tool works ?

**Comment by mrsrikanth** [comment]
Hello,

The compilation issues with latest Kaldi has been resolved.
You should be able to use it now.

Thanks,
Srikanth

**Comment by ajinkyakulkarni14** [comment]
Thank You @mrsrikanth !
